### PR TITLE
Fix compilation with Xcode >= 16.0

### PR DESCRIPTION
**Pull request by jkrukowski**
I came across the issue when my package (which indirectly depends on `Jinja`) was built on swiftpackageindex.com
The build resulted in error, more info here:
https://swiftpackageindex.com/builds/EF6D0DF9-542C-47AE-9D1A-D16C8790BF71

Looks like the easiest fix is to provide a separate `Package.swift` for Swift 6.0. To repro it locally you can try to build it from command line using:

```bash
env DEVELOPER_DIR=/Applications/Xcode-16.1.0.app xcrun xcodebuild -skipMacroValidation -skipPackagePluginValidation build -scheme Jinja -destination platform=macOS,arch=arm64 OTHER_SWIFT_FLAGS=-strict-concurrency=complete
```

Without `Package@swift-6.0.swift` this should give an error, with it, it should build.

### CODE REVIEW

**Comment by jkrukowski** [comment]
Same happens in swift-transformers repo https://swiftpackageindex.com/builds/F6095453-30D2-4175-8FBF-E28D9AD440FE it fails to compile because seems like swift 6 has `BareSlashRegexLiterals` enabled by default https://github.com/swiftlang/swift-evolution/blob/main/proposals/0354-regex-literals.md#source-compatibility

**Comment by jkrukowski** [comment]
Another solution would be to wrap regex literals in `#/.../#`, let me know how you want to proceed @maiqingqiang

**Comment by maiqingqiang** [comment]
Thank you, I'll review it tonight.

**Comment by maiqingqiang** [comment]
Adding Package@swift-6.0.swift only solved the build issue, it didn't really make Jinja support Swift 6, right?

**Comment by jkrukowski** [comment]
> Adding [Package@swift-6.0.swift](mailto:Package@swift-6.0.swift) only solved the build issue, it didn't really make Jinja support Swift 6, right?

yes, that's correct, it makes Jinja compile with >= Xcode 16.0, I'll update the PR title

**Comment by maiqingqiang** [comment]
> Another solution would be to wrap regex literals in `#/.../#`, let me know how you want to proceed @maiqingqiang

Perhaps we could do it this way?
https://github.com/swiftlang/swift-evolution/blob/main/proposals/0362-piecemeal-future-features.md

```swift
#if compiler(>=5.7)
  #if hasFeature(BareSlashRegexLiterals)
  let regex = /.../
  #else
  let regex = #/.../#
  #endif
#else
let regex = try NSRegularExpression(pattern: "...")
#endif
```

**Comment by maiqingqiang** [comment]
> > > Another solution would be to wrap regex literals in `#/.../#`, let me know how you want to proceed @maiqingqiang
> > 
> > 
> > Perhaps we could do it this way? https://github.com/swiftlang/swift-evolution/blob/main/proposals/0362-piecemeal-future-features.md
> > ```swift
> > #if compiler(>=5.7)
> >   #if hasFeature(BareSlashRegexLiterals)
> >   let regex = /.../
> >   #else
> >   let regex = #/.../#
> >   #endif
> > #else
> > let regex = try NSRegularExpression(pattern: "...")
> > #endif
> > ```
> 
> Looks good, however:
> 
> * this might be a bit excessive because this package will not work with Swift < 5.8, that's the version which is specified in Package.swift
> * why don't we wrap every regex literal between `#` so for example [this line](https://github.com/maiqingqiang/Jinja/blob/b435eb62b0d3d5f34167ec70a128355486981712/Sources/Lexer.swift#L156C9-L156C37) becomes `.replacing(#/{##}/#, with: "")`wdyt? This way we don't need additional package.swift for swift 6 only

Sure, you can directly use `.replacing(#/{##}/#, with: "")`.

**Review by maiqingqiang — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
